#! /bin/sh
#
# $Id$
#

echo "run($1, $2)..."

test "$#" = 2 || exit 1
test -r "$2/$1.stdout" || exit 1
test -r "$2/$1.stderr" || exit 1
test -r "$2/$1.exit" || exit 1

test "$1" = 3 && sleep 5

exit $1
